const COURSES_DETAILS = [
  {
    id: 1,
    title: "Aprenda a elegir los alimentos",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$430",
    course_id: 1,
    video: null,
  },
  {
    id: 2,
    title: "Conociendo mis límites mentales",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$300",
    course_id: 1,
    video: null,
  },
  {
    id: 3,
    title: "El esfuerzo en dirección al objetivo",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$240",
    course_id: 1,
    video: null,
  },
  {
    id: 4,
    title: "A bailar",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$230",
    course_id: 2,
    video: null,
  },
  {
    id: 5,
    title: "La fuerza también ayuda",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$300",
    course_id: 2,
    video: null,
  },
  {
    id: 6,
    title: "Organizando mis actividades",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$280",
    course_id: 2,
    video: null,
  },
  {
    id: 7,
    title: "Pequeñas acciones",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$0",
    course_id: 3,
    video: null,
  },
  {
    id: 8,
    title: "Divulgando el cuidado de la naturaleza",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$310",
    course_id: 3,
    video: null,
  },
  {
    id: 9,
    title: "Que les dejamos a nuestros hijos",
    bg: "https://i.ibb.co/930Xd43/OIP.jpg",
    price: "$5000",
    course_id: 3,
    video: "https://www.youtube.com/embed/bm19sPg6JAM",
  },
]

export default COURSES_DETAILS
