export { default as CATEGORIES } from "./categories"
export { default as FEEDBACK } from "./feedback"
export { default as PRODUCTS } from "./products"
export { default as COURSES } from "./courses"
export { default as COURSES_DETAILS } from "./coursesDetails"
